# Load the common variables repo
resources:
  repositories:
  - repository: az-packer-common
    type: github
    endpoint: Azure
    name: kevinpz/az-packer-common

# Source the variables
variables:
# Load the common variables
- template: common-variables.yml@az-packer-common
# Define the list of replication region
- name: replication_regions_list
  ${{ if eq(variables['replication_regions'], '') }}:
      value: ${{ variables.location }}
  ${{ else }}:
      value: '${{ variables.location }},${{ variables.replication_regions }}'

parameters:
# The source image publisher to use
- name: src_image_publisher
  type: string 
# The source image offer to use
- name: src_image_offer
  type: string 
# The source image sku to use
- name: src_image_sku
  type: string 
# The destination image name
- name: dst_image_name
  type: string 
# The destination image offer
- name: dst_image_offer
  type: string 
# The destination image sku
- name: dst_image_sku
  type: string 
# The type of image to build
- name: image_type
  type: string 
  values :
  - Linux
  - Windows
# VM SKU for building the image
- name: image_build_sku
  type: string 
  default: 'Standard_D2ds_v4'

stages:
# Create the image definition in the compute image gallery
- stage: Deploy
  pool: azure-vm
      # Uncomment to use Microsoft managed runners
      # vmImage: 'ubuntu-latest'

  jobs:
  - job: Deploy
    steps:
      - checkout: az-packer-pipeline-template

      # Download Terraform binary
      - task: TerraformInstaller@0
        displayName: Install terraform
        inputs:
          terraformVersion: '1.3.1'

      # Init Terraform backend and download providers
      - task: TerraformCLI@0
        displayName: Terraform init
        inputs:
          workingDirectory: build
          command: init

          # Configure the backend to store the .tfstate file
          backendType: azurerm
          backendServiceArm: '${{ variables.sc_name }}'
          backendAzureRmSubscriptionId: '${{ variables.backend_subscription_id }}'
          backendAzureRmResourceGroupName: '${{ variables.stg_rg_name }}'
          backendAzureRmStorageAccountName: '${{ variables.stg_name }}'
          backendAzureRmContainerName: '${{ variables.stg_container_name }}'
          backendAzureRmKey: '$(System.TeamProject)/$(Build.Repository.Name).tfstate'

      # Deploy Terraform ressources
      - task: TerraformCLI@0
        displayName: Terraform apply
        inputs:
          workingDirectory: build
          command: apply
          environmentServiceName: '${{ variables.sc_name }}'
          providerAzureRmSubscriptionId: '${{ variables.depl_subscription_id }}'
          commandOptions: '-var "location=${{ variables.location }}" -var "rg_name=${{ variables.rg_name }}" -var "gallery_name=${{ variables.gallery_name }}" -var "dst_image_name=${{ parameters.dst_image_name }}" -var "image_type=${{ parameters.image_type }}" -var "dst_image_publisher=${{ variables.dst_image_publisher }}" -var "dst_image_offer=${{ parameters.dst_image_offer }}" -var "dst_image_sku=${{ parameters.dst_image_sku }}"'

# Build the image
- stage: Build
  pool: azure-vm
      # Uncomment to use Microsoft managed runners
      # vmImage: 'ubuntu-latest'
  jobs:
  - job: Build
    steps:
      # Checkout the repositories
      - checkout: self
        path: s/az-packer-image
      - checkout: az-packer-pipeline-template

      # Get the secrets for Packer
      - task: AzureCLI@2
        displayName: Get Secrets
        name: get_secrets 
        inputs:
          azureSubscription: '${{ variables.sc_name }}'
          addSpnToEnvironment: true
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "##vso[task.setvariable variable=client_id;isOutput=true;issecret=true]$servicePrincipalId" 
            echo "##vso[task.setvariable variable=client_secret;isOutput=true;issecret=true]$servicePrincipalKey"
            echo "##vso[task.setvariable variable=tenant_id;isOutput=true;issecret=true]$tenantId"
            az account show

      # Build the VM image
      - task: PackerBuild@1
        displayName: Build image
        inputs:
          connectedServiceName: '${{ variables.sc_name }}'
          templateType: custom
          customTemplateLocation: ./az-packer-pipeline-template/packer/image_template.json
          isManagedImage: false
          packerVersion: '1.8.3'
        env:
          client_id: $(get_secrets.client_id)
          client_secret: $(get_secrets.client_secret)
          tenant_id: $(get_secrets.tenant_id)
          subscription_id: ${{ variables.depl_subscription_id }}
          rg_name: ${{ variables.rg_name }}
          gallery_name: ${{ variables.gallery_name }}
          dst_image_name: ${{ parameters.dst_image_name }}
          location: ${{ variables.location }}
          replication_regions: ${{ variables.replication_regions_list }}
          src_image_publisher: ${{ parameters.src_image_publisher }}
          src_image_offer: ${{ parameters.src_image_offer }}
          src_image_sku: ${{ parameters.src_image_sku }}
          image_build_sku: ${{ parameters.image_build_sku }}
          image_type: ${{ parameters.image_type }}
          img_stg_type: ${{ variables.img_stg_type }}
          image_version: $(Build.SourceBranchName)
          rg_vnet_name: ${{ variables.rg_vnet_name }}
          vnet_name: ${{ variables.vnet_name }}
          subnet_name: ${{ variables.subnet_name }}
          replica_count: ${{ variables.replica_count }}
          
# Deploy a VM to validate the image
- stage: Validate
  pool: azure-vm
      # Uncomment to use Microsoft managed runners
      # vmImage: 'ubuntu-latest'

  jobs:
  - job: Deploy
    steps:
      # Checkout the repositories
      - checkout: self
        path: s/az-packer-image
      - checkout: az-packer-pipeline-template

      # Download Terraform binary
      - task: TerraformInstaller@0
        displayName: Install terraform
        inputs:
          terraformVersion: '1.3.1'

      # Generate a random password
      - task: Bash@3
        displayName: Generate VM password
        name: create_password 
        inputs:
          targetType: 'inline'
          script: echo "##vso[task.setvariable variable=vm_password;isOutput=true;issecret=true]$(date +%s | sha256sum | base64 | head -c 32)" 
      
      # Init Terraform backend and download providers
      - task: TerraformCLI@0
        displayName: Terraform init
        inputs:
          workingDirectory: validate
          command: init
          # Configure the backend to store the .tfstate file
          backendType: azurerm
          backendServiceArm: '${{ variables.sc_name }}'
          backendAzureRmSubscriptionId: '${{ variables.backend_subscription_id }}'
          backendAzureRmResourceGroupName: '${{ variables.stg_rg_name }}'
          backendAzureRmStorageAccountName: '${{ variables.stg_name }}'
          backendAzureRmContainerName: '${{ variables.stg_container_name }}'
          backendAzureRmKey: '$(System.TeamProject)/$(Build.Repository.Name)_validate.tfstate'

      # Deploy Terraform ressources
      - task: TerraformCLI@0
        displayName: Terraform apply
        inputs:
          workingDirectory: validate
          command: apply
          environmentServiceName: '${{ variables.sc_name }}'
          providerAzureRmSubscriptionId: '${{ variables.depl_subscription_id }}'
          commandOptions: '-var "location=${{ variables.location }}" -var "rg_name=${{ variables.rg_name }}" -var "gallery_name=${{ variables.gallery_name }}" -var "dst_image_name=${{ parameters.dst_image_name }}" -var "image_type=${{ parameters.image_type }}" -var "rg_vnet_name=${{ variables.rg_vnet_name }}" -var "vnet_name=${{ variables.vnet_name }}" -var "subnet_name=${{ variables.subnet_name }}" -var "image_build_sku=${{ parameters.image_build_sku }}" -var "image_version=$(Build.SourceBranchName)"'
        env:
          TF_VAR_vm_password: $(create_password.vm_password)

      # Get VM IP
      - task: TerraformCLI@0
        displayName: Terraform output
        name: get_ip 
        inputs:
          workingDirectory: validate
          command: output
          environmentServiceName: '${{ variables.sc_name }}'
          providerAzureRmSubscriptionId: '${{ variables.depl_subscription_id }}'
          #commandOptions: '-var "location=${{ variables.location }}" -var "rg_name=${{ variables.rg_name }}" -var "gallery_name=${{ variables.gallery_name }}" -var "dst_image_name=${{ parameters.dst_image_name }}" -var "image_type=${{ parameters.image_type }}" -var "rg_vnet_name=${{ variables.rg_vnet_name }}" -var "vnet_name=${{ variables.vnet_name }}" -var "subnet_name=${{ variables.subnet_name }}" -var "image_build_sku=${{ parameters.image_build_sku }}" -var "image_version=$(Build.SourceBranchName)"'
        #env:
        #  TF_VAR_vm_password: $(create_password.vm_password)

      # Use ansible to validate the image
      - task: Ansible@0
        displayName: Validate the image
        inputs:
          ansibleInterface: 'agentMachine'
          playbookPathOnAgentMachine: 'az-packer-image/validate/playbook.yml'
          failOnStdErr: false
          inventoriesAgentMachine: inlineContent
          inventoryInlineContentAgentMachine: |
            [packer]
            ${TF_OUT_VM_IP_ADDR}
          args: --extra-vars "ansible_user=adminuser ansible_password=${vm_password}"
        env:
          vm_password: $(create_password.vm_password)
          ANSIBLE_HOST_KEY_CHECKING: False

      # Destroy Terraform ressources
      - task: TerraformCLI@0
        displayName: Terraform destroy
        condition: always()
        inputs:
          workingDirectory: validate
          command: destroy
          environmentServiceName: '${{ variables.sc_name }}'
          providerAzureRmSubscriptionId: '${{ variables.depl_subscription_id }}'
          commandOptions: '-var "location=${{ variables.location }}" -var "rg_name=${{ variables.rg_name }}" -var "gallery_name=${{ variables.gallery_name }}" -var "dst_image_name=${{ parameters.dst_image_name }}" -var "image_type=${{ parameters.image_type }}" -var "rg_vnet_name=${{ variables.rg_vnet_name }}" -var "vnet_name=${{ variables.vnet_name }}" -var "subnet_name=${{ variables.subnet_name }}" -var "image_build_sku=${{ parameters.image_build_sku }}" -var "image_version=$(Build.SourceBranchName)"'
        env:
          TF_VAR_vm_password: $(create_password.vm_password)

# Promote the image to latest
- stage: Promote
  pool: azure-vm
      # Uncomment to use Microsoft managed runners
      # vmImage: 'ubuntu-latest'
  jobs:
  - job: Promote
    steps:
      # Checkout the repositories
      - checkout: self
        path: s/az-packer-image
      - checkout: az-packer-pipeline-template

      # Promote the image to the latest
      - task: AzureCLI@2
        displayName: Set image to latest
        name: promote_latest 
        inputs:
          azureSubscription: '${{ variables.sc_name }}'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az sig image-version update -g ${{ variables.rg_name }} --gallery-name ${{ variables.gallery_name }} \
              --gallery-image-definition ${{ parameters.dst_image_name }} --gallery-image-version $(Build.SourceBranchName) \
              --add excludeFromLatest=false