sed -i -e "s/<subscription_id>/${subscription_id}/g" ../template/image_template.json
sed -i -e "s/<rg_name>/${rg_name}/g" ../template/image_template.json
sed -i -e "s/<image_name>/${image_name}/g" ../template/image_template.json
sed -i -e "s/<gallery_name>/${gallery_name}/g" ../template/image_template.json
sed -i -e "s/<region_1>/${location}/g" ../template/image_template.json
sed -i -e "s/<id_name>/${id_name}/g" ../template/image_template.json
sed -i -e "s/<src_image_publisher>/${src_image_publisher}/g" ../template/image_template.json
sed -i -e "s/<src_image_offer>/${src_image_offer}/g" ../template/image_template.json
sed -i -e "s/<src_image_sku>/${src_image_sku}/g" ../template/image_template.json
sed -i -e "s/<image_build_sku>/${image_build_sku}/g" ../template/image_template.json
sed -i -e "s/<image_build_size>/${image_build_size}/g" ../template/image_template.json